[package]
name = "postgres"
version = "0.0.3"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }

wit-bindgen = "0.60.0"

url = "2.5.8"
postgres-protocol = "0.6.12"
bytes = "1.12.1"
fallible-iterator = "0.2"

schemars = "1.2.2"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
