services:
  harness:
    ports:
      - '9000:9000'
    environment:
      - 'RUST_LOG=debug'
    configs:
      - source: 'test'
        target: '/config.yml'
    build:
      target: 'builder'
    volumes:
      - './harness:/source'

configs:
  test:
    content: |
      agent:
        model: 'ollama/gemma4'
        prompt: 'You must help us with some simple tasks'
      services:
        test_http:
          type: 'http'
          triggers:
            incoming_request:
              path: '/testolo'
              prompt: 'You received the following message from the user. Please do something'
        second_http:
          type: 'http'
          port: 9000
          triggers:
            put_incoming_request:
              method: 'put'
              path: '/puttolo'
              prompt: 'The request you receive contains a number. Concatenate the number with the string PUPUPPAPA'
            post_incoming_request:
              method: 'post'
              path: '/postolo'
              prompt: 'You received the following message from the user. Please do something'
