package olivia:tools;

world tool-world {
  enum permission {
    network,
    file-system
  }

  record tool-info {
    name: string,
    description: string,
    schema: string,
    permissions: list<permission>,
    env: list<string>
  }

  enum tool-output-state {
    done,
    error
  }

  record tool-output {
    state: tool-output-state,
    content: string
  }

  export info: func() -> tool-info;
  export run: func(input: string) -> tool-output; 
}
